# Generated by Django 4.2.9 on 2026-04-01 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerchild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerchild',
            name='custody_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workerchild',
            name='gender',
            field=models.CharField(blank=True, choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], max_length=10),
        ),
        migrations.AddField(
            model_name='workerchild',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerchild',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workerchild',
            name='lives_with_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workerchild',
            name='receives_allowance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerchild',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='workerchild',
            table='children_dev',
        ),
    ]
