# Generated by Django 4.2.9 on 2026-04-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_estimated_budget_project_estimated_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='site_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to='core.project')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.worker')),
            ],
            options={
                'db_table': 'project_site_photos_dev',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('agreed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='freelancer_contracts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='core.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_agreements', to='core.project')),
            ],
            options={
                'db_table': 'freelancer_agreements_dev',
                'ordering': ['-created_at'],
                'unique_together': {('freelancer', 'project')},
            },
        ),
        migrations.AddField(
            model_name='freelancerpayment',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.freelanceragreement'),
        ),
        migrations.CreateModel(
            name='ProjectWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.project')),
            ],
            options={
                'db_table': 'project_work_logs_dev',
                'ordering': ['-log_date'],
                'unique_together': {('project', 'log_date')},
            },
        ),
    ]
