# Generated by Django 4.2.9 on 2026-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectsitephoto_freelanceragreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
