# Generated by Django 4.2.9 on 2026-04-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_freelanceragreement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wage_type',
            field=models.CharField(choices=[('hourly', 'שעתי'), ('daily', 'יומי'), ('monthly', 'חודשי')], default='hourly', max_length=10),
        ),
    ]
