# Generated by Django 4.2.9 on 2026-04-09 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_worker_daily_rate_alter_worker_wage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('approved', 'אושר'), ('rejected', 'נדחה')], default='pending', max_length=20)),
                ('manager_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='core.worker')),
            ],
            options={
                'db_table': 'shift_corrections_dev',
                'ordering': ['-created_at'],
            },
        ),
    ]
