# Generated by Django 4.2.9 on 2026-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shiftcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='has_pension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='has_study_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'בעלים'), ('manager', 'מנהל'), ('worker', 'עובד'), ('freelancer', 'פרילנסר')], default='worker', max_length=20),
        ),
    ]
