# Generated by Django 4.2.9 on 2026-05-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_worker_has_pension_worker_has_study_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceragreement',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freelanceragreement',
            name='contract_file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='freelancerpayment',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerpayment',
            name='invoice_file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='materialinvoice',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialinvoice',
            name='delivery_note_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialinvoice',
            name='delivery_note_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='materialinvoice',
            name='image_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materialinvoice',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectsitephoto',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectsitephoto',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='materialinvoice',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.worker'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='projectsitephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='site_photos/%Y/%m/'),
        ),
    ]
