# Generated by Django 4.2.9 on 2026-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_freelanceragreement_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='tax_id_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
