# Generated by Django 4.2.9 on 2026-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_freelancer_tax_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('setting_key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('setting_value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'הגדרת שכר',
                'verbose_name_plural': 'הגדרות שכר',
                'db_table': 'payroll_settings_dev',
                'ordering': ['setting_key'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_index', models.IntegerField(unique=True)),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income ceiling in ₪. Leave blank for the top bracket (no limit).', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal: 0.20 means 20%. 0.50 for top bracket includes mas yesef.', max_digits=6)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'מדרגת מס',
                'verbose_name_plural': 'מדרגות מס',
                'db_table': 'payroll_tax_brackets_dev',
                'ordering': ['bracket_index'],
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payslip_cloudinary_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payslip_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payslip_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
