# Generated by Django 4.2.9 on 2026-05-10 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_payrollsetting_payrolltaxbracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='default_withholding_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default ניכוי מס במקור rate (%). 0 = פטור.', max_digits=5),
        ),
        migrations.CreateModel(
            name='FreelancerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('tax_certificate', 'אישור ניכוי מס במקור'), ('tax_exemption', 'אישור פטור מניכוי מס'), ('osek_certificate', 'אישור עוסק מורשה'), ('id_copy', 'צילום תעודת זהות'), ('insurance', 'ביטוח חבות מקצועית'), ('license', 'רישיון מקצועי'), ('bank_confirmation', 'אישור ניהול חשבון בנק'), ('other', 'אחר')], default='other', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.freelancer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_freelancer_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'מסמך קבלן משנה',
                'db_table': 'freelancer_documents_dev',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
